# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_basic_example.ipynb.

# %% auto 0
__all__ = ['arrange_talk']

# %% ../nbs/01_basic_example.ipynb 2
import datetime

# %% ../nbs/01_basic_example.ipynb 4
def arrange_talk(speaker:str, # The name of the speaker
                 title:str, # The title of the talk that will be given
                 talk_date:datetime.date=datetime.date.today() # The date that the speaker will be giving the talk
                ) -> str: # The output is a string that gives a human readable output of the information provided
    "This is a really important docstring that conveys useful information!"
    return f"{speaker} will be talking about {title} on {talk_date}"
