# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_introduction.ipynb.

# %% auto 0
__all__ = ['do_something']

# %% ../nbs/00_introduction.ipynb 23
def do_something(var1:str, # A description of var1
                 var2:int=42 # Including the types as well
                ) -> str: # Describe the thing that is being returned
    "A signature that describes the function"
    return value
