# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/madpy',
                'doc_host': 'https://kevinbird15.github.io',
                'git_url': 'https://github.com/kevinbird15/madpy',
                'lib_path': 'madpy'},
  'syms': {'madpy.core': {'madpy.core.foo': ('core.html#foo', 'madpy/core.py')}}}
