# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_API_Integration.ipynb.

# %% auto 0
__all__ = ['Speaker']

# %% ../nbs/01_API_Integration.ipynb 3
import datetime

from fastcore.basics import store_attr
from fastcore.test import test_eq

from .intro import arrange_talk

# %% ../nbs/01_API_Integration.ipynb 5
class Speaker:
    "A speaker is somebody that will talk about things!"
    def __init__(self, name:str): # Test
        store_attr()
